from typing import Protocol

import fleshpy.ast as ast


class Visitor[T](Protocol):
    def visit_program(self, node: ast.Program) -> T: ...
    def visit_definition(self, node: ast.Definition) -> T: ...
    def visit_if(self, node: ast.If) -> T: ...
    def visit_cond(self, node: ast.Cond) -> T: ...
    def visit_int_literal(self, node: ast.IntLiteral) -> T: ...
    def visit_float_literal(self, node: ast.FloatLiteral) -> T: ...
    def visit_string_literal(self, node: ast.StringLiteral) -> T: ...
    def visit_boolean_literal(self, node: ast.BooleanLiteral) -> T: ...
    def visit_nil(self, node: ast.Nil) -> T: ...
    def visit_identifier(self, node: ast.Identifier) -> T: ...
    def visit_begin(self, node: ast.Begin) -> T: ...
    def visit_lambda(self, node: ast.Lambda) -> T: ...
    def visit_application(self, node: ast.Application) -> T: ...
